apiVersion: v1
kind: Service
metadata:
  name: {{ include "responses-api-store.fullname" . }}
  labels:
    {{- include "responses-api-store.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "responses-api-store.selectorLabels" . | nindent 4 }}
  ports:
    - name: grpc
      port: {{ include "responses-api-store.servicePort" . }}
      targetPort: grpc