// Generated by tonic-build; `async_trait` expansions trip clippy::double_must_use on Rust 1.99+.
#[allow(clippy::double_must_use)]
pub mod v1 {
    tonic::include_proto!("responsesapistore.v1");
}

pub use v1::responses_api_store_client::ResponsesApiStoreClient;
pub use v1::responses_api_store_server::{ResponsesApiStore, ResponsesApiStoreServer};
