// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: responsesapistore/v1/store.proto

package responsesapistorev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StoredResponse mirrors the gateway-owned record used by Responses API compatible services.
type StoredResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ResponseId string                 `protobuf:"bytes,1,opt,name=response_id,json=responseId,proto3" json:"response_id,omitempty"`
	Upstream   string                 `protobuf:"bytes,2,opt,name=upstream,proto3" json:"upstream,omitempty"`
	// OpenAI-compatible response object JSON.
	ResponseJson string `protobuf:"bytes,3,opt,name=response_json,json=responseJson,proto3" json:"response_json,omitempty"`
	// Materialized conversation input items as JSON strings.
	InputJson []string `protobuf:"bytes,4,rep,name=input_json,json=inputJson,proto3" json:"input_json,omitempty"`
	// Upstream request body retained for background workers.
	PendingUpstreamRequestJson *string `protobuf:"bytes,5,opt,name=pending_upstream_request_json,json=pendingUpstreamRequestJson,proto3,oneof" json:"pending_upstream_request_json,omitempty"`
	UpstreamAuthorization      *string `protobuf:"bytes,6,opt,name=upstream_authorization,json=upstreamAuthorization,proto3,oneof" json:"upstream_authorization,omitempty"`
	// Unix timestamp (seconds) when the job was enqueued.
	EnqueuedAt    *int64 `protobuf:"varint,7,opt,name=enqueued_at,json=enqueuedAt,proto3,oneof" json:"enqueued_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoredResponse) Reset() {
	*x = StoredResponse{}
	mi := &file_responsesapistore_v1_store_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoredResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoredResponse) ProtoMessage() {}

func (x *StoredResponse) ProtoReflect() protoreflect.Message {
	mi := &file_responsesapistore_v1_store_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoredResponse.ProtoReflect.Descriptor instead.
func (*StoredResponse) Descriptor() ([]byte, []int) {
	return file_responsesapistore_v1_store_proto_rawDescGZIP(), []int{0}
}

func (x *StoredResponse) GetResponseId() string {
	if x != nil {
		return x.ResponseId
	}
	return ""
}

func (x *StoredResponse) GetUpstream() string {
	if x != nil {
		return x.Upstream
	}
	return ""
}

func (x *StoredResponse) GetResponseJson() string {
	if x != nil {
		return x.ResponseJson
	}
	return ""
}

func (x *StoredResponse) GetInputJson() []string {
	if x != nil {
		return x.InputJson
	}
	return nil
}

func (x *StoredResponse) GetPendingUpstreamRequestJson() string {
	if x != nil && x.PendingUpstreamRequestJson != nil {
		return *x.PendingUpstreamRequestJson
	}
	return ""
}

func (x *StoredResponse) GetUpstreamAuthorization() string {
	if x != nil && x.UpstreamAuthorization != nil {
		return *x.UpstreamAuthorization
	}
	return ""
}

func (x *StoredResponse) GetEnqueuedAt() int64 {
	if x != nil && x.EnqueuedAt != nil {
		return *x.EnqueuedAt
	}
	return 0
}

type StoreResponseRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Record *StoredResponse        `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	// TTL override in seconds; zero uses server default.
	TtlSeconds    uint64 `protobuf:"varint,2,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreResponseRequest) Reset() {
	*x = StoreResponseRequest{}
	mi := &file_responsesapistore_v1_store_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreResponseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreResponseRequest) ProtoMessage() {}

func (x *StoreResponseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_responsesapistore_v1_store_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreResponseRequest.ProtoReflect.Descriptor instead.
func (*StoreResponseRequest) Descriptor() ([]byte, []int) {
	return file_responsesapistore_v1_store_proto_rawDescGZIP(), []int{1}
}

func (x *StoreResponseRequest) GetRecord() *StoredResponse {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *StoreResponseRequest) GetTtlSeconds() uint64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type StoreResponseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreResponseResponse) Reset() {
	*x = StoreResponseResponse{}
	mi := &file_responsesapistore_v1_store_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreResponseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreResponseResponse) ProtoMessage() {}

func (x *StoreResponseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_responsesapistore_v1_store_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreResponseResponse.ProtoReflect.Descriptor instead.
func (*StoreResponseResponse) Descriptor() ([]byte, []int) {
	return file_responsesapistore_v1_store_proto_rawDescGZIP(), []int{2}
}

type GetResponseRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ResponseId string                 `protobuf:"bytes,1,opt,name=response_id,json=responseId,proto3" json:"response_id,omitempty"`
	// When true, stale queued background responses may be reconciled to failed.
	ReconcileStale bool `protobuf:"varint,2,opt,name=reconcile_stale,json=reconcileStale,proto3" json:"reconcile_stale,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetResponseRequest) Reset() {
	*x = GetResponseRequest{}
	mi := &file_responsesapistore_v1_store_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponseRequest) ProtoMessage() {}

func (x *GetResponseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_responsesapistore_v1_store_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponseRequest.ProtoReflect.Descriptor instead.
func (*GetResponseRequest) Descriptor() ([]byte, []int) {
	return file_responsesapistore_v1_store_proto_rawDescGZIP(), []int{3}
}

func (x *GetResponseRequest) GetResponseId() string {
	if x != nil {
		return x.ResponseId
	}
	return ""
}

func (x *GetResponseRequest) GetReconcileStale() bool {
	if x != nil {
		return x.ReconcileStale
	}
	return false
}

type GetResponseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *StoredResponse        `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponseResponse) Reset() {
	*x = GetResponseResponse{}
	mi := &file_responsesapistore_v1_store_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponseResponse) ProtoMessage() {}

func (x *GetResponseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_responsesapistore_v1_store_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponseResponse.ProtoReflect.Descriptor instead.
func (*GetResponseResponse) Descriptor() ([]byte, []int) {
	return file_responsesapistore_v1_store_proto_rawDescGZIP(), []int{4}
}

func (x *GetResponseResponse) GetRecord() *StoredResponse {
	if x != nil {
		return x.Record
	}
	return nil
}

type UpdateResponseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *StoredResponse        `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	TtlSeconds    uint64                 `protobuf:"varint,2,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponseRequest) Reset() {
	*x = UpdateResponseRequest{}
	mi := &file_responsesapistore_v1_store_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponseRequest) ProtoMessage() {}

func (x *UpdateResponseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_responsesapistore_v1_store_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponseRequest.ProtoReflect.Descriptor instead.
func (*UpdateResponseRequest) Descriptor() ([]byte, []int) {
	return file_responsesapistore_v1_store_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateResponseRequest) GetRecord() *StoredResponse {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *UpdateResponseRequest) GetTtlSeconds() uint64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type UpdateResponseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponseResponse) Reset() {
	*x = UpdateResponseResponse{}
	mi := &file_responsesapistore_v1_store_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponseResponse) ProtoMessage() {}

func (x *UpdateResponseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_responsesapistore_v1_store_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponseResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponseResponse) Descriptor() ([]byte, []int) {
	return file_responsesapistore_v1_store_proto_rawDescGZIP(), []int{6}
}

type DeleteResponseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResponseId    string                 `protobuf:"bytes,1,opt,name=response_id,json=responseId,proto3" json:"response_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponseRequest) Reset() {
	*x = DeleteResponseRequest{}
	mi := &file_responsesapistore_v1_store_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponseRequest) ProtoMessage() {}

func (x *DeleteResponseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_responsesapistore_v1_store_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponseRequest.ProtoReflect.Descriptor instead.
func (*DeleteResponseRequest) Descriptor() ([]byte, []int) {
	return file_responsesapistore_v1_store_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteResponseRequest) GetResponseId() string {
	if x != nil {
		return x.ResponseId
	}
	return ""
}

type DeleteResponseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponseResponse) Reset() {
	*x = DeleteResponseResponse{}
	mi := &file_responsesapistore_v1_store_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponseResponse) ProtoMessage() {}

func (x *DeleteResponseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_responsesapistore_v1_store_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponseResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponseResponse) Descriptor() ([]byte, []int) {
	return file_responsesapistore_v1_store_proto_rawDescGZIP(), []int{8}
}

type EnqueueBackgroundJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *StoredResponse        `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueBackgroundJobRequest) Reset() {
	*x = EnqueueBackgroundJobRequest{}
	mi := &file_responsesapistore_v1_store_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueBackgroundJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueBackgroundJobRequest) ProtoMessage() {}

func (x *EnqueueBackgroundJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_responsesapistore_v1_store_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueBackgroundJobRequest.ProtoReflect.Descriptor instead.
func (*EnqueueBackgroundJobRequest) Descriptor() ([]byte, []int) {
	return file_responsesapistore_v1_store_proto_rawDescGZIP(), []int{9}
}

func (x *EnqueueBackgroundJobRequest) GetRecord() *StoredResponse {
	if x != nil {
		return x.Record
	}
	return nil
}

type EnqueueBackgroundJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueBackgroundJobResponse) Reset() {
	*x = EnqueueBackgroundJobResponse{}
	mi := &file_responsesapistore_v1_store_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueBackgroundJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueBackgroundJobResponse) ProtoMessage() {}

func (x *EnqueueBackgroundJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_responsesapistore_v1_store_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueBackgroundJobResponse.ProtoReflect.Descriptor instead.
func (*EnqueueBackgroundJobResponse) Descriptor() ([]byte, []int) {
	return file_responsesapistore_v1_store_proto_rawDescGZIP(), []int{10}
}

type ClaimBackgroundJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumerGroup string                 `protobuf:"bytes,1,opt,name=consumer_group,json=consumerGroup,proto3" json:"consumer_group,omitempty"`
	ConsumerName  string                 `protobuf:"bytes,2,opt,name=consumer_name,json=consumerName,proto3" json:"consumer_name,omitempty"`
	// Maximum jobs to return in one call.
	Count uint32 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	// Block up to this many milliseconds waiting for new jobs (0 = no block).
	BlockMs uint32 `protobuf:"varint,4,opt,name=block_ms,json=blockMs,proto3" json:"block_ms,omitempty"`
	// Reclaim jobs idle longer than this many milliseconds via XAUTOCLAIM.
	AutoclaimMinIdleMs uint32 `protobuf:"varint,5,opt,name=autoclaim_min_idle_ms,json=autoclaimMinIdleMs,proto3" json:"autoclaim_min_idle_ms,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ClaimBackgroundJobsRequest) Reset() {
	*x = ClaimBackgroundJobsRequest{}
	mi := &file_responsesapistore_v1_store_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimBackgroundJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimBackgroundJobsRequest) ProtoMessage() {}

func (x *ClaimBackgroundJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_responsesapistore_v1_store_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimBackgroundJobsRequest.ProtoReflect.Descriptor instead.
func (*ClaimBackgroundJobsRequest) Descriptor() ([]byte, []int) {
	return file_responsesapistore_v1_store_proto_rawDescGZIP(), []int{11}
}

func (x *ClaimBackgroundJobsRequest) GetConsumerGroup() string {
	if x != nil {
		return x.ConsumerGroup
	}
	return ""
}

func (x *ClaimBackgroundJobsRequest) GetConsumerName() string {
	if x != nil {
		return x.ConsumerName
	}
	return ""
}

func (x *ClaimBackgroundJobsRequest) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ClaimBackgroundJobsRequest) GetBlockMs() uint32 {
	if x != nil {
		return x.BlockMs
	}
	return 0
}

func (x *ClaimBackgroundJobsRequest) GetAutoclaimMinIdleMs() uint32 {
	if x != nil {
		return x.AutoclaimMinIdleMs
	}
	return 0
}

type BackgroundJob struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	StreamId   string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	ResponseId string                 `protobuf:"bytes,2,opt,name=response_id,json=responseId,proto3" json:"response_id,omitempty"`
	Record     *StoredResponse        `protobuf:"bytes,3,opt,name=record,proto3" json:"record,omitempty"`
	// True when the job was reclaimed from another consumer.
	Autoclaimed bool `protobuf:"varint,4,opt,name=autoclaimed,proto3" json:"autoclaimed,omitempty"`
	// Idle time in milliseconds when autoclaimed.
	IdleMs        *uint64 `protobuf:"varint,5,opt,name=idle_ms,json=idleMs,proto3,oneof" json:"idle_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackgroundJob) Reset() {
	*x = BackgroundJob{}
	mi := &file_responsesapistore_v1_store_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackgroundJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackgroundJob) ProtoMessage() {}

func (x *BackgroundJob) ProtoReflect() protoreflect.Message {
	mi := &file_responsesapistore_v1_store_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackgroundJob.ProtoReflect.Descriptor instead.
func (*BackgroundJob) Descriptor() ([]byte, []int) {
	return file_responsesapistore_v1_store_proto_rawDescGZIP(), []int{12}
}

func (x *BackgroundJob) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *BackgroundJob) GetResponseId() string {
	if x != nil {
		return x.ResponseId
	}
	return ""
}

func (x *BackgroundJob) GetRecord() *StoredResponse {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *BackgroundJob) GetAutoclaimed() bool {
	if x != nil {
		return x.Autoclaimed
	}
	return false
}

func (x *BackgroundJob) GetIdleMs() uint64 {
	if x != nil && x.IdleMs != nil {
		return *x.IdleMs
	}
	return 0
}

type ClaimBackgroundJobsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Jobs  []*BackgroundJob       `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	// Stream IDs claimed from Redis but not hydrated (e.g. transient load errors).
	// Entries remain in the consumer group PEL until acknowledged or autoclaimed.
	PendingStreamIds []string `protobuf:"bytes,2,rep,name=pending_stream_ids,json=pendingStreamIds,proto3" json:"pending_stream_ids,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ClaimBackgroundJobsResponse) Reset() {
	*x = ClaimBackgroundJobsResponse{}
	mi := &file_responsesapistore_v1_store_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimBackgroundJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimBackgroundJobsResponse) ProtoMessage() {}

func (x *ClaimBackgroundJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_responsesapistore_v1_store_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimBackgroundJobsResponse.ProtoReflect.Descriptor instead.
func (*ClaimBackgroundJobsResponse) Descriptor() ([]byte, []int) {
	return file_responsesapistore_v1_store_proto_rawDescGZIP(), []int{13}
}

func (x *ClaimBackgroundJobsResponse) GetJobs() []*BackgroundJob {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *ClaimBackgroundJobsResponse) GetPendingStreamIds() []string {
	if x != nil {
		return x.PendingStreamIds
	}
	return nil
}

type AcknowledgeBackgroundJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	ConsumerGroup string                 `protobuf:"bytes,2,opt,name=consumer_group,json=consumerGroup,proto3" json:"consumer_group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcknowledgeBackgroundJobRequest) Reset() {
	*x = AcknowledgeBackgroundJobRequest{}
	mi := &file_responsesapistore_v1_store_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcknowledgeBackgroundJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcknowledgeBackgroundJobRequest) ProtoMessage() {}

func (x *AcknowledgeBackgroundJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_responsesapistore_v1_store_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcknowledgeBackgroundJobRequest.ProtoReflect.Descriptor instead.
func (*AcknowledgeBackgroundJobRequest) Descriptor() ([]byte, []int) {
	return file_responsesapistore_v1_store_proto_rawDescGZIP(), []int{14}
}

func (x *AcknowledgeBackgroundJobRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *AcknowledgeBackgroundJobRequest) GetConsumerGroup() string {
	if x != nil {
		return x.ConsumerGroup
	}
	return ""
}

type AcknowledgeBackgroundJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcknowledgeBackgroundJobResponse) Reset() {
	*x = AcknowledgeBackgroundJobResponse{}
	mi := &file_responsesapistore_v1_store_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcknowledgeBackgroundJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcknowledgeBackgroundJobResponse) ProtoMessage() {}

func (x *AcknowledgeBackgroundJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_responsesapistore_v1_store_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcknowledgeBackgroundJobResponse.ProtoReflect.Descriptor instead.
func (*AcknowledgeBackgroundJobResponse) Descriptor() ([]byte, []int) {
	return file_responsesapistore_v1_store_proto_rawDescGZIP(), []int{15}
}

type EnsureConsumerGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumerGroup string                 `protobuf:"bytes,1,opt,name=consumer_group,json=consumerGroup,proto3" json:"consumer_group,omitempty"`
	// Stream ID to start reading from when creating the group ("0-0" or "$").
	StartId       string `protobuf:"bytes,2,opt,name=start_id,json=startId,proto3" json:"start_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureConsumerGroupRequest) Reset() {
	*x = EnsureConsumerGroupRequest{}
	mi := &file_responsesapistore_v1_store_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureConsumerGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureConsumerGroupRequest) ProtoMessage() {}

func (x *EnsureConsumerGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_responsesapistore_v1_store_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureConsumerGroupRequest.ProtoReflect.Descriptor instead.
func (*EnsureConsumerGroupRequest) Descriptor() ([]byte, []int) {
	return file_responsesapistore_v1_store_proto_rawDescGZIP(), []int{16}
}

func (x *EnsureConsumerGroupRequest) GetConsumerGroup() string {
	if x != nil {
		return x.ConsumerGroup
	}
	return ""
}

func (x *EnsureConsumerGroupRequest) GetStartId() string {
	if x != nil {
		return x.StartId
	}
	return ""
}

type EnsureConsumerGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Created       bool                   `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureConsumerGroupResponse) Reset() {
	*x = EnsureConsumerGroupResponse{}
	mi := &file_responsesapistore_v1_store_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureConsumerGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureConsumerGroupResponse) ProtoMessage() {}

func (x *EnsureConsumerGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_responsesapistore_v1_store_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureConsumerGroupResponse.ProtoReflect.Descriptor instead.
func (*EnsureConsumerGroupResponse) Descriptor() ([]byte, []int) {
	return file_responsesapistore_v1_store_proto_rawDescGZIP(), []int{17}
}

func (x *EnsureConsumerGroupResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

type GetBackgroundQueueStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumerGroup string                 `protobuf:"bytes,1,opt,name=consumer_group,json=consumerGroup,proto3" json:"consumer_group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBackgroundQueueStatsRequest) Reset() {
	*x = GetBackgroundQueueStatsRequest{}
	mi := &file_responsesapistore_v1_store_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBackgroundQueueStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBackgroundQueueStatsRequest) ProtoMessage() {}

func (x *GetBackgroundQueueStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_responsesapistore_v1_store_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBackgroundQueueStatsRequest.ProtoReflect.Descriptor instead.
func (*GetBackgroundQueueStatsRequest) Descriptor() ([]byte, []int) {
	return file_responsesapistore_v1_store_proto_rawDescGZIP(), []int{18}
}

func (x *GetBackgroundQueueStatsRequest) GetConsumerGroup() string {
	if x != nil {
		return x.ConsumerGroup
	}
	return ""
}

type GetBackgroundQueueStatsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Jobs waiting to be claimed by a worker.
	Pending uint64 `protobuf:"varint,1,opt,name=pending,proto3" json:"pending,omitempty"`
	// Jobs claimed but not yet acknowledged (in-flight).
	InProgress uint64 `protobuf:"varint,2,opt,name=in_progress,json=inProgress,proto3" json:"in_progress,omitempty"`
	// Scalar for HPA/KEDA (recommended: pending + in_progress).
	Workload      uint64 `protobuf:"varint,3,opt,name=workload,proto3" json:"workload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBackgroundQueueStatsResponse) Reset() {
	*x = GetBackgroundQueueStatsResponse{}
	mi := &file_responsesapistore_v1_store_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBackgroundQueueStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBackgroundQueueStatsResponse) ProtoMessage() {}

func (x *GetBackgroundQueueStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_responsesapistore_v1_store_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBackgroundQueueStatsResponse.ProtoReflect.Descriptor instead.
func (*GetBackgroundQueueStatsResponse) Descriptor() ([]byte, []int) {
	return file_responsesapistore_v1_store_proto_rawDescGZIP(), []int{19}
}

func (x *GetBackgroundQueueStatsResponse) GetPending() uint64 {
	if x != nil {
		return x.Pending
	}
	return 0
}

func (x *GetBackgroundQueueStatsResponse) GetInProgress() uint64 {
	if x != nil {
		return x.InProgress
	}
	return 0
}

func (x *GetBackgroundQueueStatsResponse) GetWorkload() uint64 {
	if x != nil {
		return x.Workload
	}
	return 0
}

type ReconcileStaleResponseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResponseId    string                 `protobuf:"bytes,1,opt,name=response_id,json=responseId,proto3" json:"response_id,omitempty"`
	StaleSeconds  int64                  `protobuf:"varint,2,opt,name=stale_seconds,json=staleSeconds,proto3" json:"stale_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconcileStaleResponseRequest) Reset() {
	*x = ReconcileStaleResponseRequest{}
	mi := &file_responsesapistore_v1_store_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcileStaleResponseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcileStaleResponseRequest) ProtoMessage() {}

func (x *ReconcileStaleResponseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_responsesapistore_v1_store_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcileStaleResponseRequest.ProtoReflect.Descriptor instead.
func (*ReconcileStaleResponseRequest) Descriptor() ([]byte, []int) {
	return file_responsesapistore_v1_store_proto_rawDescGZIP(), []int{20}
}

func (x *ReconcileStaleResponseRequest) GetResponseId() string {
	if x != nil {
		return x.ResponseId
	}
	return ""
}

func (x *ReconcileStaleResponseRequest) GetStaleSeconds() int64 {
	if x != nil {
		return x.StaleSeconds
	}
	return 0
}

type ReconcileStaleResponseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *StoredResponse        `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	Reconciled    bool                   `protobuf:"varint,2,opt,name=reconciled,proto3" json:"reconciled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconcileStaleResponseResponse) Reset() {
	*x = ReconcileStaleResponseResponse{}
	mi := &file_responsesapistore_v1_store_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcileStaleResponseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcileStaleResponseResponse) ProtoMessage() {}

func (x *ReconcileStaleResponseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_responsesapistore_v1_store_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcileStaleResponseResponse.ProtoReflect.Descriptor instead.
func (*ReconcileStaleResponseResponse) Descriptor() ([]byte, []int) {
	return file_responsesapistore_v1_store_proto_rawDescGZIP(), []int{21}
}

func (x *ReconcileStaleResponseResponse) GetRecord() *StoredResponse {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *ReconcileStaleResponseResponse) GetReconciled() bool {
	if x != nil {
		return x.Reconciled
	}
	return false
}

type GenerateResponseIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateResponseIdRequest) Reset() {
	*x = GenerateResponseIdRequest{}
	mi := &file_responsesapistore_v1_store_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateResponseIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateResponseIdRequest) ProtoMessage() {}

func (x *GenerateResponseIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_responsesapistore_v1_store_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateResponseIdRequest.ProtoReflect.Descriptor instead.
func (*GenerateResponseIdRequest) Descriptor() ([]byte, []int) {
	return file_responsesapistore_v1_store_proto_rawDescGZIP(), []int{22}
}

type GenerateResponseIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResponseId    string                 `protobuf:"bytes,1,opt,name=response_id,json=responseId,proto3" json:"response_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateResponseIdResponse) Reset() {
	*x = GenerateResponseIdResponse{}
	mi := &file_responsesapistore_v1_store_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateResponseIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateResponseIdResponse) ProtoMessage() {}

func (x *GenerateResponseIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_responsesapistore_v1_store_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateResponseIdResponse.ProtoReflect.Descriptor instead.
func (*GenerateResponseIdResponse) Descriptor() ([]byte, []int) {
	return file_responsesapistore_v1_store_proto_rawDescGZIP(), []int{23}
}

func (x *GenerateResponseIdResponse) GetResponseId() string {
	if x != nil {
		return x.ResponseId
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_responsesapistore_v1_store_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_responsesapistore_v1_store_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_responsesapistore_v1_store_proto_rawDescGZIP(), []int{24}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RedisOk       bool                   `protobuf:"varint,1,opt,name=redis_ok,json=redisOk,proto3" json:"redis_ok,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_responsesapistore_v1_store_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_responsesapistore_v1_store_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_responsesapistore_v1_store_proto_rawDescGZIP(), []int{25}
}

func (x *HealthResponse) GetRedisOk() bool {
	if x != nil {
		return x.RedisOk
	}
	return false
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_responsesapistore_v1_store_proto protoreflect.FileDescriptor

const file_responsesapistore_v1_store_proto_rawDesc = "" +
	"\n" +
	" responsesapistore/v1/store.proto\x12\x14responsesapistore.v1\"\x88\x03\n" +
	"\x0eStoredResponse\x12\x1f\n" +
	"\vresponse_id\x18\x01 \x01(\tR\n" +
	"responseId\x12\x1a\n" +
	"\bupstream\x18\x02 \x01(\tR\bupstream\x12#\n" +
	"\rresponse_json\x18\x03 \x01(\tR\fresponseJson\x12\x1d\n" +
	"\n" +
	"input_json\x18\x04 \x03(\tR\tinputJson\x12F\n" +
	"\x1dpending_upstream_request_json\x18\x05 \x01(\tH\x00R\x1apendingUpstreamRequestJson\x88\x01\x01\x12:\n" +
	"\x16upstream_authorization\x18\x06 \x01(\tH\x01R\x15upstreamAuthorization\x88\x01\x01\x12$\n" +
	"\venqueued_at\x18\a \x01(\x03H\x02R\n" +
	"enqueuedAt\x88\x01\x01B \n" +
	"\x1e_pending_upstream_request_jsonB\x19\n" +
	"\x17_upstream_authorizationB\x0e\n" +
	"\f_enqueued_at\"u\n" +
	"\x14StoreResponseRequest\x12<\n" +
	"\x06record\x18\x01 \x01(\v2$.responsesapistore.v1.StoredResponseR\x06record\x12\x1f\n" +
	"\vttl_seconds\x18\x02 \x01(\x04R\n" +
	"ttlSeconds\"\x17\n" +
	"\x15StoreResponseResponse\"^\n" +
	"\x12GetResponseRequest\x12\x1f\n" +
	"\vresponse_id\x18\x01 \x01(\tR\n" +
	"responseId\x12'\n" +
	"\x0freconcile_stale\x18\x02 \x01(\bR\x0ereconcileStale\"S\n" +
	"\x13GetResponseResponse\x12<\n" +
	"\x06record\x18\x01 \x01(\v2$.responsesapistore.v1.StoredResponseR\x06record\"v\n" +
	"\x15UpdateResponseRequest\x12<\n" +
	"\x06record\x18\x01 \x01(\v2$.responsesapistore.v1.StoredResponseR\x06record\x12\x1f\n" +
	"\vttl_seconds\x18\x02 \x01(\x04R\n" +
	"ttlSeconds\"\x18\n" +
	"\x16UpdateResponseResponse\"8\n" +
	"\x15DeleteResponseRequest\x12\x1f\n" +
	"\vresponse_id\x18\x01 \x01(\tR\n" +
	"responseId\"\x18\n" +
	"\x16DeleteResponseResponse\"[\n" +
	"\x1bEnqueueBackgroundJobRequest\x12<\n" +
	"\x06record\x18\x01 \x01(\v2$.responsesapistore.v1.StoredResponseR\x06record\"\x1e\n" +
	"\x1cEnqueueBackgroundJobResponse\"\xcc\x01\n" +
	"\x1aClaimBackgroundJobsRequest\x12%\n" +
	"\x0econsumer_group\x18\x01 \x01(\tR\rconsumerGroup\x12#\n" +
	"\rconsumer_name\x18\x02 \x01(\tR\fconsumerName\x12\x14\n" +
	"\x05count\x18\x03 \x01(\rR\x05count\x12\x19\n" +
	"\bblock_ms\x18\x04 \x01(\rR\ablockMs\x121\n" +
	"\x15autoclaim_min_idle_ms\x18\x05 \x01(\rR\x12autoclaimMinIdleMs\"\xd7\x01\n" +
	"\rBackgroundJob\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12\x1f\n" +
	"\vresponse_id\x18\x02 \x01(\tR\n" +
	"responseId\x12<\n" +
	"\x06record\x18\x03 \x01(\v2$.responsesapistore.v1.StoredResponseR\x06record\x12 \n" +
	"\vautoclaimed\x18\x04 \x01(\bR\vautoclaimed\x12\x1c\n" +
	"\aidle_ms\x18\x05 \x01(\x04H\x00R\x06idleMs\x88\x01\x01B\n" +
	"\n" +
	"\b_idle_ms\"\x84\x01\n" +
	"\x1bClaimBackgroundJobsResponse\x127\n" +
	"\x04jobs\x18\x01 \x03(\v2#.responsesapistore.v1.BackgroundJobR\x04jobs\x12,\n" +
	"\x12pending_stream_ids\x18\x02 \x03(\tR\x10pendingStreamIds\"e\n" +
	"\x1fAcknowledgeBackgroundJobRequest\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12%\n" +
	"\x0econsumer_group\x18\x02 \x01(\tR\rconsumerGroup\"\"\n" +
	" AcknowledgeBackgroundJobResponse\"^\n" +
	"\x1aEnsureConsumerGroupRequest\x12%\n" +
	"\x0econsumer_group\x18\x01 \x01(\tR\rconsumerGroup\x12\x19\n" +
	"\bstart_id\x18\x02 \x01(\tR\astartId\"7\n" +
	"\x1bEnsureConsumerGroupResponse\x12\x18\n" +
	"\acreated\x18\x01 \x01(\bR\acreated\"G\n" +
	"\x1eGetBackgroundQueueStatsRequest\x12%\n" +
	"\x0econsumer_group\x18\x01 \x01(\tR\rconsumerGroup\"x\n" +
	"\x1fGetBackgroundQueueStatsResponse\x12\x18\n" +
	"\apending\x18\x01 \x01(\x04R\apending\x12\x1f\n" +
	"\vin_progress\x18\x02 \x01(\x04R\n" +
	"inProgress\x12\x1a\n" +
	"\bworkload\x18\x03 \x01(\x04R\bworkload\"e\n" +
	"\x1dReconcileStaleResponseRequest\x12\x1f\n" +
	"\vresponse_id\x18\x01 \x01(\tR\n" +
	"responseId\x12#\n" +
	"\rstale_seconds\x18\x02 \x01(\x03R\fstaleSeconds\"~\n" +
	"\x1eReconcileStaleResponseResponse\x12<\n" +
	"\x06record\x18\x01 \x01(\v2$.responsesapistore.v1.StoredResponseR\x06record\x12\x1e\n" +
	"\n" +
	"reconciled\x18\x02 \x01(\bR\n" +
	"reconciled\"\x1b\n" +
	"\x19GenerateResponseIdRequest\"=\n" +
	"\x1aGenerateResponseIdResponse\x12\x1f\n" +
	"\vresponse_id\x18\x01 \x01(\tR\n" +
	"responseId\"\x0f\n" +
	"\rHealthRequest\"E\n" +
	"\x0eHealthResponse\x12\x19\n" +
	"\bredis_ok\x18\x01 \x01(\bR\aredisOk\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion2\x9b\v\n" +
	"\x11ResponsesApiStore\x12h\n" +
	"\rStoreResponse\x12*.responsesapistore.v1.StoreResponseRequest\x1a+.responsesapistore.v1.StoreResponseResponse\x12b\n" +
	"\vGetResponse\x12(.responsesapistore.v1.GetResponseRequest\x1a).responsesapistore.v1.GetResponseResponse\x12k\n" +
	"\x0eUpdateResponse\x12+.responsesapistore.v1.UpdateResponseRequest\x1a,.responsesapistore.v1.UpdateResponseResponse\x12k\n" +
	"\x0eDeleteResponse\x12+.responsesapistore.v1.DeleteResponseRequest\x1a,.responsesapistore.v1.DeleteResponseResponse\x12}\n" +
	"\x14EnqueueBackgroundJob\x121.responsesapistore.v1.EnqueueBackgroundJobRequest\x1a2.responsesapistore.v1.EnqueueBackgroundJobResponse\x12z\n" +
	"\x13ClaimBackgroundJobs\x120.responsesapistore.v1.ClaimBackgroundJobsRequest\x1a1.responsesapistore.v1.ClaimBackgroundJobsResponse\x12\x89\x01\n" +
	"\x18AcknowledgeBackgroundJob\x125.responsesapistore.v1.AcknowledgeBackgroundJobRequest\x1a6.responsesapistore.v1.AcknowledgeBackgroundJobResponse\x12z\n" +
	"\x13EnsureConsumerGroup\x120.responsesapistore.v1.EnsureConsumerGroupRequest\x1a1.responsesapistore.v1.EnsureConsumerGroupResponse\x12\x86\x01\n" +
	"\x17GetBackgroundQueueStats\x124.responsesapistore.v1.GetBackgroundQueueStatsRequest\x1a5.responsesapistore.v1.GetBackgroundQueueStatsResponse\x12\x83\x01\n" +
	"\x16ReconcileStaleResponse\x123.responsesapistore.v1.ReconcileStaleResponseRequest\x1a4.responsesapistore.v1.ReconcileStaleResponseResponse\x12w\n" +
	"\x12GenerateResponseId\x12/.responsesapistore.v1.GenerateResponseIdRequest\x1a0.responsesapistore.v1.GenerateResponseIdResponse\x12S\n" +
	"\x06Health\x12#.responsesapistore.v1.HealthRequest\x1a$.responsesapistore.v1.HealthResponseBZZXgithub.com/beranekio/responses-api-store/sdk/go/responsesapistore/v1;responsesapistorev1b\x06proto3"

var (
	file_responsesapistore_v1_store_proto_rawDescOnce sync.Once
	file_responsesapistore_v1_store_proto_rawDescData []byte
)

func file_responsesapistore_v1_store_proto_rawDescGZIP() []byte {
	file_responsesapistore_v1_store_proto_rawDescOnce.Do(func() {
		file_responsesapistore_v1_store_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_responsesapistore_v1_store_proto_rawDesc), len(file_responsesapistore_v1_store_proto_rawDesc)))
	})
	return file_responsesapistore_v1_store_proto_rawDescData
}

var file_responsesapistore_v1_store_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_responsesapistore_v1_store_proto_goTypes = []any{
	(*StoredResponse)(nil),                   // 0: responsesapistore.v1.StoredResponse
	(*StoreResponseRequest)(nil),             // 1: responsesapistore.v1.StoreResponseRequest
	(*StoreResponseResponse)(nil),            // 2: responsesapistore.v1.StoreResponseResponse
	(*GetResponseRequest)(nil),               // 3: responsesapistore.v1.GetResponseRequest
	(*GetResponseResponse)(nil),              // 4: responsesapistore.v1.GetResponseResponse
	(*UpdateResponseRequest)(nil),            // 5: responsesapistore.v1.UpdateResponseRequest
	(*UpdateResponseResponse)(nil),           // 6: responsesapistore.v1.UpdateResponseResponse
	(*DeleteResponseRequest)(nil),            // 7: responsesapistore.v1.DeleteResponseRequest
	(*DeleteResponseResponse)(nil),           // 8: responsesapistore.v1.DeleteResponseResponse
	(*EnqueueBackgroundJobRequest)(nil),      // 9: responsesapistore.v1.EnqueueBackgroundJobRequest
	(*EnqueueBackgroundJobResponse)(nil),     // 10: responsesapistore.v1.EnqueueBackgroundJobResponse
	(*ClaimBackgroundJobsRequest)(nil),       // 11: responsesapistore.v1.ClaimBackgroundJobsRequest
	(*BackgroundJob)(nil),                    // 12: responsesapistore.v1.BackgroundJob
	(*ClaimBackgroundJobsResponse)(nil),      // 13: responsesapistore.v1.ClaimBackgroundJobsResponse
	(*AcknowledgeBackgroundJobRequest)(nil),  // 14: responsesapistore.v1.AcknowledgeBackgroundJobRequest
	(*AcknowledgeBackgroundJobResponse)(nil), // 15: responsesapistore.v1.AcknowledgeBackgroundJobResponse
	(*EnsureConsumerGroupRequest)(nil),       // 16: responsesapistore.v1.EnsureConsumerGroupRequest
	(*EnsureConsumerGroupResponse)(nil),      // 17: responsesapistore.v1.EnsureConsumerGroupResponse
	(*GetBackgroundQueueStatsRequest)(nil),   // 18: responsesapistore.v1.GetBackgroundQueueStatsRequest
	(*GetBackgroundQueueStatsResponse)(nil),  // 19: responsesapistore.v1.GetBackgroundQueueStatsResponse
	(*ReconcileStaleResponseRequest)(nil),    // 20: responsesapistore.v1.ReconcileStaleResponseRequest
	(*ReconcileStaleResponseResponse)(nil),   // 21: responsesapistore.v1.ReconcileStaleResponseResponse
	(*GenerateResponseIdRequest)(nil),        // 22: responsesapistore.v1.GenerateResponseIdRequest
	(*GenerateResponseIdResponse)(nil),       // 23: responsesapistore.v1.GenerateResponseIdResponse
	(*HealthRequest)(nil),                    // 24: responsesapistore.v1.HealthRequest
	(*HealthResponse)(nil),                   // 25: responsesapistore.v1.HealthResponse
}
var file_responsesapistore_v1_store_proto_depIdxs = []int32{
	0,  // 0: responsesapistore.v1.StoreResponseRequest.record:type_name -> responsesapistore.v1.StoredResponse
	0,  // 1: responsesapistore.v1.GetResponseResponse.record:type_name -> responsesapistore.v1.StoredResponse
	0,  // 2: responsesapistore.v1.UpdateResponseRequest.record:type_name -> responsesapistore.v1.StoredResponse
	0,  // 3: responsesapistore.v1.EnqueueBackgroundJobRequest.record:type_name -> responsesapistore.v1.StoredResponse
	0,  // 4: responsesapistore.v1.BackgroundJob.record:type_name -> responsesapistore.v1.StoredResponse
	12, // 5: responsesapistore.v1.ClaimBackgroundJobsResponse.jobs:type_name -> responsesapistore.v1.BackgroundJob
	0,  // 6: responsesapistore.v1.ReconcileStaleResponseResponse.record:type_name -> responsesapistore.v1.StoredResponse
	1,  // 7: responsesapistore.v1.ResponsesApiStore.StoreResponse:input_type -> responsesapistore.v1.StoreResponseRequest
	3,  // 8: responsesapistore.v1.ResponsesApiStore.GetResponse:input_type -> responsesapistore.v1.GetResponseRequest
	5,  // 9: responsesapistore.v1.ResponsesApiStore.UpdateResponse:input_type -> responsesapistore.v1.UpdateResponseRequest
	7,  // 10: responsesapistore.v1.ResponsesApiStore.DeleteResponse:input_type -> responsesapistore.v1.DeleteResponseRequest
	9,  // 11: responsesapistore.v1.ResponsesApiStore.EnqueueBackgroundJob:input_type -> responsesapistore.v1.EnqueueBackgroundJobRequest
	11, // 12: responsesapistore.v1.ResponsesApiStore.ClaimBackgroundJobs:input_type -> responsesapistore.v1.ClaimBackgroundJobsRequest
	14, // 13: responsesapistore.v1.ResponsesApiStore.AcknowledgeBackgroundJob:input_type -> responsesapistore.v1.AcknowledgeBackgroundJobRequest
	16, // 14: responsesapistore.v1.ResponsesApiStore.EnsureConsumerGroup:input_type -> responsesapistore.v1.EnsureConsumerGroupRequest
	18, // 15: responsesapistore.v1.ResponsesApiStore.GetBackgroundQueueStats:input_type -> responsesapistore.v1.GetBackgroundQueueStatsRequest
	20, // 16: responsesapistore.v1.ResponsesApiStore.ReconcileStaleResponse:input_type -> responsesapistore.v1.ReconcileStaleResponseRequest
	22, // 17: responsesapistore.v1.ResponsesApiStore.GenerateResponseId:input_type -> responsesapistore.v1.GenerateResponseIdRequest
	24, // 18: responsesapistore.v1.ResponsesApiStore.Health:input_type -> responsesapistore.v1.HealthRequest
	2,  // 19: responsesapistore.v1.ResponsesApiStore.StoreResponse:output_type -> responsesapistore.v1.StoreResponseResponse
	4,  // 20: responsesapistore.v1.ResponsesApiStore.GetResponse:output_type -> responsesapistore.v1.GetResponseResponse
	6,  // 21: responsesapistore.v1.ResponsesApiStore.UpdateResponse:output_type -> responsesapistore.v1.UpdateResponseResponse
	8,  // 22: responsesapistore.v1.ResponsesApiStore.DeleteResponse:output_type -> responsesapistore.v1.DeleteResponseResponse
	10, // 23: responsesapistore.v1.ResponsesApiStore.EnqueueBackgroundJob:output_type -> responsesapistore.v1.EnqueueBackgroundJobResponse
	13, // 24: responsesapistore.v1.ResponsesApiStore.ClaimBackgroundJobs:output_type -> responsesapistore.v1.ClaimBackgroundJobsResponse
	15, // 25: responsesapistore.v1.ResponsesApiStore.AcknowledgeBackgroundJob:output_type -> responsesapistore.v1.AcknowledgeBackgroundJobResponse
	17, // 26: responsesapistore.v1.ResponsesApiStore.EnsureConsumerGroup:output_type -> responsesapistore.v1.EnsureConsumerGroupResponse
	19, // 27: responsesapistore.v1.ResponsesApiStore.GetBackgroundQueueStats:output_type -> responsesapistore.v1.GetBackgroundQueueStatsResponse
	21, // 28: responsesapistore.v1.ResponsesApiStore.ReconcileStaleResponse:output_type -> responsesapistore.v1.ReconcileStaleResponseResponse
	23, // 29: responsesapistore.v1.ResponsesApiStore.GenerateResponseId:output_type -> responsesapistore.v1.GenerateResponseIdResponse
	25, // 30: responsesapistore.v1.ResponsesApiStore.Health:output_type -> responsesapistore.v1.HealthResponse
	19, // [19:31] is the sub-list for method output_type
	7,  // [7:19] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_responsesapistore_v1_store_proto_init() }
func file_responsesapistore_v1_store_proto_init() {
	if File_responsesapistore_v1_store_proto != nil {
		return
	}
	file_responsesapistore_v1_store_proto_msgTypes[0].OneofWrappers = []any{}
	file_responsesapistore_v1_store_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_responsesapistore_v1_store_proto_rawDesc), len(file_responsesapistore_v1_store_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_responsesapistore_v1_store_proto_goTypes,
		DependencyIndexes: file_responsesapistore_v1_store_proto_depIdxs,
		MessageInfos:      file_responsesapistore_v1_store_proto_msgTypes,
	}.Build()
	File_responsesapistore_v1_store_proto = out.File
	file_responsesapistore_v1_store_proto_goTypes = nil
	file_responsesapistore_v1_store_proto_depIdxs = nil
}
