// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: responsesapistore/v1/store.proto

package responsesapistorev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ResponsesApiStore_StoreResponse_FullMethodName            = "/responsesapistore.v1.ResponsesApiStore/StoreResponse"
	ResponsesApiStore_GetResponse_FullMethodName              = "/responsesapistore.v1.ResponsesApiStore/GetResponse"
	ResponsesApiStore_UpdateResponse_FullMethodName           = "/responsesapistore.v1.ResponsesApiStore/UpdateResponse"
	ResponsesApiStore_DeleteResponse_FullMethodName           = "/responsesapistore.v1.ResponsesApiStore/DeleteResponse"
	ResponsesApiStore_EnqueueBackgroundJob_FullMethodName     = "/responsesapistore.v1.ResponsesApiStore/EnqueueBackgroundJob"
	ResponsesApiStore_ClaimBackgroundJobs_FullMethodName      = "/responsesapistore.v1.ResponsesApiStore/ClaimBackgroundJobs"
	ResponsesApiStore_AcknowledgeBackgroundJob_FullMethodName = "/responsesapistore.v1.ResponsesApiStore/AcknowledgeBackgroundJob"
	ResponsesApiStore_EnsureConsumerGroup_FullMethodName      = "/responsesapistore.v1.ResponsesApiStore/EnsureConsumerGroup"
	ResponsesApiStore_ReconcileStaleResponse_FullMethodName   = "/responsesapistore.v1.ResponsesApiStore/ReconcileStaleResponse"
	ResponsesApiStore_GenerateResponseId_FullMethodName       = "/responsesapistore.v1.ResponsesApiStore/GenerateResponseId"
	ResponsesApiStore_Health_FullMethodName                   = "/responsesapistore.v1.ResponsesApiStore/Health"
)

// ResponsesApiStoreClient is the client API for ResponsesApiStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// gRPC service for storing OpenAI Responses API objects, tracking request state,
// and distributing background jobs to workers.
type ResponsesApiStoreClient interface {
	// Response persistence
	StoreResponse(ctx context.Context, in *StoreResponseRequest, opts ...grpc.CallOption) (*StoreResponseResponse, error)
	GetResponse(ctx context.Context, in *GetResponseRequest, opts ...grpc.CallOption) (*GetResponseResponse, error)
	UpdateResponse(ctx context.Context, in *UpdateResponseRequest, opts ...grpc.CallOption) (*UpdateResponseResponse, error)
	DeleteResponse(ctx context.Context, in *DeleteResponseRequest, opts ...grpc.CallOption) (*DeleteResponseResponse, error)
	// Background job lifecycle
	EnqueueBackgroundJob(ctx context.Context, in *EnqueueBackgroundJobRequest, opts ...grpc.CallOption) (*EnqueueBackgroundJobResponse, error)
	ClaimBackgroundJobs(ctx context.Context, in *ClaimBackgroundJobsRequest, opts ...grpc.CallOption) (*ClaimBackgroundJobsResponse, error)
	AcknowledgeBackgroundJob(ctx context.Context, in *AcknowledgeBackgroundJobRequest, opts ...grpc.CallOption) (*AcknowledgeBackgroundJobResponse, error)
	EnsureConsumerGroup(ctx context.Context, in *EnsureConsumerGroupRequest, opts ...grpc.CallOption) (*EnsureConsumerGroupResponse, error)
	// Maintenance and utilities
	ReconcileStaleResponse(ctx context.Context, in *ReconcileStaleResponseRequest, opts ...grpc.CallOption) (*ReconcileStaleResponseResponse, error)
	GenerateResponseId(ctx context.Context, in *GenerateResponseIdRequest, opts ...grpc.CallOption) (*GenerateResponseIdResponse, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type responsesApiStoreClient struct {
	cc grpc.ClientConnInterface
}

func NewResponsesApiStoreClient(cc grpc.ClientConnInterface) ResponsesApiStoreClient {
	return &responsesApiStoreClient{cc}
}

func (c *responsesApiStoreClient) StoreResponse(ctx context.Context, in *StoreResponseRequest, opts ...grpc.CallOption) (*StoreResponseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreResponseResponse)
	err := c.cc.Invoke(ctx, ResponsesApiStore_StoreResponse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *responsesApiStoreClient) GetResponse(ctx context.Context, in *GetResponseRequest, opts ...grpc.CallOption) (*GetResponseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponseResponse)
	err := c.cc.Invoke(ctx, ResponsesApiStore_GetResponse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *responsesApiStoreClient) UpdateResponse(ctx context.Context, in *UpdateResponseRequest, opts ...grpc.CallOption) (*UpdateResponseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateResponseResponse)
	err := c.cc.Invoke(ctx, ResponsesApiStore_UpdateResponse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *responsesApiStoreClient) DeleteResponse(ctx context.Context, in *DeleteResponseRequest, opts ...grpc.CallOption) (*DeleteResponseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponseResponse)
	err := c.cc.Invoke(ctx, ResponsesApiStore_DeleteResponse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *responsesApiStoreClient) EnqueueBackgroundJob(ctx context.Context, in *EnqueueBackgroundJobRequest, opts ...grpc.CallOption) (*EnqueueBackgroundJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnqueueBackgroundJobResponse)
	err := c.cc.Invoke(ctx, ResponsesApiStore_EnqueueBackgroundJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *responsesApiStoreClient) ClaimBackgroundJobs(ctx context.Context, in *ClaimBackgroundJobsRequest, opts ...grpc.CallOption) (*ClaimBackgroundJobsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClaimBackgroundJobsResponse)
	err := c.cc.Invoke(ctx, ResponsesApiStore_ClaimBackgroundJobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *responsesApiStoreClient) AcknowledgeBackgroundJob(ctx context.Context, in *AcknowledgeBackgroundJobRequest, opts ...grpc.CallOption) (*AcknowledgeBackgroundJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcknowledgeBackgroundJobResponse)
	err := c.cc.Invoke(ctx, ResponsesApiStore_AcknowledgeBackgroundJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *responsesApiStoreClient) EnsureConsumerGroup(ctx context.Context, in *EnsureConsumerGroupRequest, opts ...grpc.CallOption) (*EnsureConsumerGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnsureConsumerGroupResponse)
	err := c.cc.Invoke(ctx, ResponsesApiStore_EnsureConsumerGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *responsesApiStoreClient) ReconcileStaleResponse(ctx context.Context, in *ReconcileStaleResponseRequest, opts ...grpc.CallOption) (*ReconcileStaleResponseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReconcileStaleResponseResponse)
	err := c.cc.Invoke(ctx, ResponsesApiStore_ReconcileStaleResponse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *responsesApiStoreClient) GenerateResponseId(ctx context.Context, in *GenerateResponseIdRequest, opts ...grpc.CallOption) (*GenerateResponseIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateResponseIdResponse)
	err := c.cc.Invoke(ctx, ResponsesApiStore_GenerateResponseId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *responsesApiStoreClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, ResponsesApiStore_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResponsesApiStoreServer is the server API for ResponsesApiStore service.
// All implementations must embed UnimplementedResponsesApiStoreServer
// for forward compatibility.
//
// gRPC service for storing OpenAI Responses API objects, tracking request state,
// and distributing background jobs to workers.
type ResponsesApiStoreServer interface {
	// Response persistence
	StoreResponse(context.Context, *StoreResponseRequest) (*StoreResponseResponse, error)
	GetResponse(context.Context, *GetResponseRequest) (*GetResponseResponse, error)
	UpdateResponse(context.Context, *UpdateResponseRequest) (*UpdateResponseResponse, error)
	DeleteResponse(context.Context, *DeleteResponseRequest) (*DeleteResponseResponse, error)
	// Background job lifecycle
	EnqueueBackgroundJob(context.Context, *EnqueueBackgroundJobRequest) (*EnqueueBackgroundJobResponse, error)
	ClaimBackgroundJobs(context.Context, *ClaimBackgroundJobsRequest) (*ClaimBackgroundJobsResponse, error)
	AcknowledgeBackgroundJob(context.Context, *AcknowledgeBackgroundJobRequest) (*AcknowledgeBackgroundJobResponse, error)
	EnsureConsumerGroup(context.Context, *EnsureConsumerGroupRequest) (*EnsureConsumerGroupResponse, error)
	// Maintenance and utilities
	ReconcileStaleResponse(context.Context, *ReconcileStaleResponseRequest) (*ReconcileStaleResponseResponse, error)
	GenerateResponseId(context.Context, *GenerateResponseIdRequest) (*GenerateResponseIdResponse, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedResponsesApiStoreServer()
}

// UnimplementedResponsesApiStoreServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedResponsesApiStoreServer struct{}

func (UnimplementedResponsesApiStoreServer) StoreResponse(context.Context, *StoreResponseRequest) (*StoreResponseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StoreResponse not implemented")
}
func (UnimplementedResponsesApiStoreServer) GetResponse(context.Context, *GetResponseRequest) (*GetResponseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetResponse not implemented")
}
func (UnimplementedResponsesApiStoreServer) UpdateResponse(context.Context, *UpdateResponseRequest) (*UpdateResponseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateResponse not implemented")
}
func (UnimplementedResponsesApiStoreServer) DeleteResponse(context.Context, *DeleteResponseRequest) (*DeleteResponseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteResponse not implemented")
}
func (UnimplementedResponsesApiStoreServer) EnqueueBackgroundJob(context.Context, *EnqueueBackgroundJobRequest) (*EnqueueBackgroundJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnqueueBackgroundJob not implemented")
}
func (UnimplementedResponsesApiStoreServer) ClaimBackgroundJobs(context.Context, *ClaimBackgroundJobsRequest) (*ClaimBackgroundJobsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClaimBackgroundJobs not implemented")
}
func (UnimplementedResponsesApiStoreServer) AcknowledgeBackgroundJob(context.Context, *AcknowledgeBackgroundJobRequest) (*AcknowledgeBackgroundJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcknowledgeBackgroundJob not implemented")
}
func (UnimplementedResponsesApiStoreServer) EnsureConsumerGroup(context.Context, *EnsureConsumerGroupRequest) (*EnsureConsumerGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnsureConsumerGroup not implemented")
}
func (UnimplementedResponsesApiStoreServer) ReconcileStaleResponse(context.Context, *ReconcileStaleResponseRequest) (*ReconcileStaleResponseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReconcileStaleResponse not implemented")
}
func (UnimplementedResponsesApiStoreServer) GenerateResponseId(context.Context, *GenerateResponseIdRequest) (*GenerateResponseIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateResponseId not implemented")
}
func (UnimplementedResponsesApiStoreServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedResponsesApiStoreServer) mustEmbedUnimplementedResponsesApiStoreServer() {}
func (UnimplementedResponsesApiStoreServer) testEmbeddedByValue()                           {}

// UnsafeResponsesApiStoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ResponsesApiStoreServer will
// result in compilation errors.
type UnsafeResponsesApiStoreServer interface {
	mustEmbedUnimplementedResponsesApiStoreServer()
}

func RegisterResponsesApiStoreServer(s grpc.ServiceRegistrar, srv ResponsesApiStoreServer) {
	// If the following call panics, it indicates UnimplementedResponsesApiStoreServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ResponsesApiStore_ServiceDesc, srv)
}

func _ResponsesApiStore_StoreResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreResponseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResponsesApiStoreServer).StoreResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResponsesApiStore_StoreResponse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResponsesApiStoreServer).StoreResponse(ctx, req.(*StoreResponseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResponsesApiStore_GetResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResponseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResponsesApiStoreServer).GetResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResponsesApiStore_GetResponse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResponsesApiStoreServer).GetResponse(ctx, req.(*GetResponseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResponsesApiStore_UpdateResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateResponseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResponsesApiStoreServer).UpdateResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResponsesApiStore_UpdateResponse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResponsesApiStoreServer).UpdateResponse(ctx, req.(*UpdateResponseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResponsesApiStore_DeleteResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteResponseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResponsesApiStoreServer).DeleteResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResponsesApiStore_DeleteResponse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResponsesApiStoreServer).DeleteResponse(ctx, req.(*DeleteResponseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResponsesApiStore_EnqueueBackgroundJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnqueueBackgroundJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResponsesApiStoreServer).EnqueueBackgroundJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResponsesApiStore_EnqueueBackgroundJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResponsesApiStoreServer).EnqueueBackgroundJob(ctx, req.(*EnqueueBackgroundJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResponsesApiStore_ClaimBackgroundJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimBackgroundJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResponsesApiStoreServer).ClaimBackgroundJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResponsesApiStore_ClaimBackgroundJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResponsesApiStoreServer).ClaimBackgroundJobs(ctx, req.(*ClaimBackgroundJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResponsesApiStore_AcknowledgeBackgroundJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcknowledgeBackgroundJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResponsesApiStoreServer).AcknowledgeBackgroundJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResponsesApiStore_AcknowledgeBackgroundJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResponsesApiStoreServer).AcknowledgeBackgroundJob(ctx, req.(*AcknowledgeBackgroundJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResponsesApiStore_EnsureConsumerGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnsureConsumerGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResponsesApiStoreServer).EnsureConsumerGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResponsesApiStore_EnsureConsumerGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResponsesApiStoreServer).EnsureConsumerGroup(ctx, req.(*EnsureConsumerGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResponsesApiStore_ReconcileStaleResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReconcileStaleResponseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResponsesApiStoreServer).ReconcileStaleResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResponsesApiStore_ReconcileStaleResponse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResponsesApiStoreServer).ReconcileStaleResponse(ctx, req.(*ReconcileStaleResponseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResponsesApiStore_GenerateResponseId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateResponseIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResponsesApiStoreServer).GenerateResponseId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResponsesApiStore_GenerateResponseId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResponsesApiStoreServer).GenerateResponseId(ctx, req.(*GenerateResponseIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResponsesApiStore_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResponsesApiStoreServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResponsesApiStore_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResponsesApiStoreServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ResponsesApiStore_ServiceDesc is the grpc.ServiceDesc for ResponsesApiStore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ResponsesApiStore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "responsesapistore.v1.ResponsesApiStore",
	HandlerType: (*ResponsesApiStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StoreResponse",
			Handler:    _ResponsesApiStore_StoreResponse_Handler,
		},
		{
			MethodName: "GetResponse",
			Handler:    _ResponsesApiStore_GetResponse_Handler,
		},
		{
			MethodName: "UpdateResponse",
			Handler:    _ResponsesApiStore_UpdateResponse_Handler,
		},
		{
			MethodName: "DeleteResponse",
			Handler:    _ResponsesApiStore_DeleteResponse_Handler,
		},
		{
			MethodName: "EnqueueBackgroundJob",
			Handler:    _ResponsesApiStore_EnqueueBackgroundJob_Handler,
		},
		{
			MethodName: "ClaimBackgroundJobs",
			Handler:    _ResponsesApiStore_ClaimBackgroundJobs_Handler,
		},
		{
			MethodName: "AcknowledgeBackgroundJob",
			Handler:    _ResponsesApiStore_AcknowledgeBackgroundJob_Handler,
		},
		{
			MethodName: "EnsureConsumerGroup",
			Handler:    _ResponsesApiStore_EnsureConsumerGroup_Handler,
		},
		{
			MethodName: "ReconcileStaleResponse",
			Handler:    _ResponsesApiStore_ReconcileStaleResponse_Handler,
		},
		{
			MethodName: "GenerateResponseId",
			Handler:    _ResponsesApiStore_GenerateResponseId_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _ResponsesApiStore_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "responsesapistore/v1/store.proto",
}
